<a href="https://colab.research.google.com/github/KDNaigan/KD/blob/main/Naigan_Hands_on_Activity_7_1_Data_Collection_and_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MODULE 7: Data Wrangling with Pandas

Submitted by: Naigan, King Darryl C.

Submitted on: Febuary 24, 2026

# Exercise 1

In [74]:
import pandas as pd

# Read each CSV file
facebook = pd.read_csv("fb.csv")
apple = pd.read_csv("aapl.csv")
amazon = pd.read_csv("amzn.csv")
netflix = pd.read_csv("nflx.csv")
google = pd.read_csv("goog.csv")

# Add ticker
facebook["ticker"] = "FB"
apple["ticker"] = "AAPL"
amazon["ticker"] = "AMZN"
netflix["ticker"] = "NFLX"
google["ticker"] = "GOOGL"

# combine them into one dataframe
faang = pd.concat([facebook, apple, amazon, netflix, google],
                  axis=0,
                  ignore_index=True)

# save to CSV
faang.to_csv("faang.csv", index=False)

# Display
faang.head(10)

         date    open    high       low   close    volume ticker
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903     FB
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563     FB
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896     FB
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535     FB
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726     FB
5  2018-01-09  188.70  188.80  187.1000  187.87  12393057     FB
6  2018-01-10  186.94  187.89  185.6300  187.84  10529894     FB
7  2018-01-11  188.40  188.40  187.3800  187.77   9588587     FB
8  2018-01-12  178.06  181.48  177.4000  179.37  77551299     FB
9  2018-01-16  181.50  181.75  178.0400  178.39  36183842     FB

# Exercise 2

In [75]:
import pandas as pd

faang = pd.read_csv("faang.csv")
print(faang)

            date     open     high        low    close    volume ticker
0     2018-01-02   177.68   181.58   177.5500   181.42  18151903     FB
1     2018-01-03   181.88   184.78   181.3300   184.67  16886563     FB
2     2018-01-04   184.90   186.21   184.0996   184.33  13880896     FB
3     2018-01-05   185.59   186.90   184.9300   186.85  13574535     FB
4     2018-01-08   187.20   188.90   186.3300   188.28  17994726     FB
...          ...      ...      ...        ...      ...       ...    ...
1250  2018-12-24   973.90  1003.54   970.1100   976.22   1590328  GOOGL
1251  2018-12-26   989.01  1040.00   983.0000  1039.46   2373270  GOOGL
1252  2018-12-27  1017.15  1043.89   997.0000  1043.88   2109777  GOOGL
1253  2018-12-28  1049.62  1055.56  1033.1000  1037.08   1413772  GOOGL
1254  2018-12-31  1050.96  1052.70  1023.5900  1035.61   1493722  GOOGL

[1255 rows x 7 columns]

In [76]:
import pandas as pd

# Convert data types
faang["date"] = pd.to_datetime(faang["date"])
faang["volume"] = faang["volume"].astype(int)

# Sort by date then ticker
faang = faang.sort_values(by=["date", "ticker"])

# Display first 5 rows
faang.head()

           date       open       high        low      close    volume ticker
251  2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
502  2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
0    2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
1004 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564  GOOGL
753  2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX

In [77]:
t7_volume = faang.nlargest(7, "volume")

t7_volume

          date      open      high       low     close     volume ticker
142 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
53  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
57  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
54  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
433 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
496 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
463 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [78]:
faang.sort_values(by="volume", ascending=False).head(7)

          date      open      high       low     close     volume ticker
142 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
53  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
57  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
54  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
433 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
496 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
463 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [79]:
faang_long = pd.melt(
    faang,
    id_vars=["date", "ticker"],
    var_name="variable",
    value_name="value"
)

faang_long.head()

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02  GOOGL     open  1048.3400
4 2018-01-02   NFLX     open   196.1000

# Exercise 3

In [93]:
pip install requests beautifulsoup4

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.1.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)

In [100]:
pip install pandas requests lxml

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (6.0.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.1.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [104]:
import requests
from bs4 import BeautifulSoup

def getData(url):
    r = requests.get(url)
    print(r.status_code)
    return r.text

url = "https://phapi.online/members/"

html = getData(url)

200

In [106]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL
url = "https://phapi.online/members/"

# Add headers to avoid blocking
headers = {
    "User-Agent": "Mozilla/5.0"
}

# Request page
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

# Lists to store data
names = []
addresses = []
contacts = []

# Inspect the site structure — adjust selectors if needed
members = soup.find_all("div", class_="elementor-widget-container")

for member in members:
    text = member.get_text(separator="|", strip=True).split("|")

    # Basic parsing (adjust based on actual page structure)
    if len(text) >= 2:
        names.append(text[0])
        addresses.append(text[1])
        contacts.append(text[2] if len(text) > 2 else "Unknown")

# Create DataFrame
hospitals = pd.DataFrame({
    "name": names,
    "address": addresses,
    "contact": contacts
})

# Save CSV
hospitals.to_csv("hospitals.csv", index=False)

print(hospitals.head())

Empty DataFrame
Columns: [name, address, contact]
Index: []

In [108]:
# Load CSV
df = pd.read_csv("hospitals.csv")

# Remove duplicates
df = df.drop_duplicates()

# Clean whitespace
df["name"] = df["name"].str.strip()
df["address"] = df["address"].str.strip()
df["contact"] = df["contact"].astype(str).str.strip()

# Replace missing values
df.fillna("Unknown", inplace=True)

print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     0 non-null      object
 1   address  0 non-null      object
 2   contact  0 non-null      object
dtypes: object(3)
memory usage: 132.0+ bytes
None
Empty DataFrame
Columns: [name, address, contact]
Index: []

# 7.2 Conclusion:

**Important data science skills like data collection, data cleaning and transformation with Python were utilized in this activity. Combining data, changing types of data, ranking data, statistical analysis, and web crawling data available on the Internet, we received insight into working with real-world data. The techniques play a critical role in taking unorganized data and transforming them into a structured and useful format to be used in analysis and decision making. On the whole, the dissemination allowed to reinforce our knowledge of the manipulation of data and preprocessing data analytics.**